gibs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('accounts/', include('allauth.urls')),
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'
urlpatterns = [
    path('', views.ShareView.as_view(), name="share"),
path('share-detail/<int:pk>/', views.ShareDetailView.as_view(), name="share_detail"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'
# Create your models here.

restaurant/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Restaurant(models.Model):
    "店舗テーブル"
    #storeからnameへ,TextFieldからCharField
    id = models.CharField(verbose_name='店舗ID',max_length=10,primary_key=True)
    name = models.CharField(verbose_name='店舗名',max_length=20)
    category = models.CharField(verbose_name='カテゴリ',max_length=10)
    address = models.CharField(verbose_name='メールアドレス',max_length=128)
    latitude = models.FloatField(verbose_name='緯度')
    longitude =  models.FloatField(verbose_name='経度')
    url = models.CharField(verbose_name='URL',max_length=500)
    image_url = models.CharField(verbose_name='画像url',max_length=500)
    store_update_date  = models.DateTimeField(verbose_name='更新日時',auto_now=True)


    class Meta:
        verbose_name_plural = 'restaurant'

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

restaurant/views.py
from django.views import generic

from .models import restaurant

# Create your views here.

class ShareView(generic.ListView):
    model = restaurant
    template_name = "share.html"

class ShareDetailView(generic.DetailView):
    model = restaurant
    template_name = 'share_detail.html'

restaurant/templates/base.html
{% load static %}
{% block extrahead %}
{% endblock %}
<!DOCTYPE html>

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!--Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>

<body>

<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'restaurant:share' %}">牛飲馬食</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% block active_inquiry %} {% endblock %}">
                        <a class="nav-link" href="{% url 'restaurant:share' %}">共有一覧</a>
                    </li>
                </ul>
                 <ul class="navbar-nav ml-auto">
                     {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                    </li>
                     {% else %}
                     <li class="nav-item {% block active_signup %}{% endblock %}">
                        <a class="nav-link" href="{% url 'account_signup' %}">サインアップ</a>
                    </li>
                     <li class="nav-item {% block active_login %}{% endblock %}">
                        <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
                    </li>
                     {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block header%}{% endblock %}

    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{message}}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>
    {% endif %}

    {% block contents%}{% endblock %}

    <!-- Footer -->
    <footer class="py-5 bg-black">
        <div class="container">
            <p class="m-0 text-center text-white small">Copyright &copy;威風堂々 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core  JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</div>
</body>
</html>

restaurant/templates/share.html
{% extends 'base.html' %}

{% load static %}

{% block title %}共有一覧 | Share List{% endblock %}

{% block active_restaurant %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <h1 class="col-lg-8 col-md-10 mx-auto">共有一覧</h1>
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                </div>
                {% for restaurant in restaurant %}
                <div class="post-preview">
                    <a href="{% url 'restaurant:share_detail' restaurant.pk %}">
                        <h2 class="post-title">
                            店舗名：{{restaurant.store}}
                        </h2>
                    </a>
                </div>
                <hr>
                {% empty %}
                <p>店舗がありません。</p>
                {% endfor %}

                <!-- ページネーション処理 -->

                {% if is_paginated %}
                <ul class="pagination">
                    <!-- 前ページへのリンク -->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number}}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    <!-- ページ数表示 -->
                    {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 次ページへのリンク -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

restaurant/templates/share_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}共有詳細| 牛飲馬食{% endblock %}

{% block active_restaurant %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <h1 class="mb-4">共有詳細</h1>
        <div class="row">
            <div class="col-3">
                <strong>店舗名</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>ジャンル</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

         <hr>

        <div class="row">
            <div class="col-3">
                <strong>住所</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>URL</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

         <hr>

        <div class="row">
            <div class="col-3">
                <strong>電話番号</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

         <hr>

        <div class="row">
            <div class="col-3">
                <strong>画像URL</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

         <hr>

        <div class="row">
            <div class="col-3">
                <strong>登録日時</strong>
            </div>
            <div class="col-9">

            </div>
        </div>

        <a class="btn btn-success mt-5 mb-3" href="#">編集</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="#">削除</a>
        <a class="btn btn-secondary mt-5 ml-2 mb-3" href="{% url 'restaurant:share'%}">戻る</a>

    </div>
</div>
{% endblock %}